name: ci
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # in case a browser hangs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - uses: maxmilton/action-setup-playwright@v1
        with:
          browsers: chromium, firefox, webkit # optional
          headless: true # optional

      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test-e2e